// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sensors_WPF__.NET_03._1_.Sensors;

#nullable disable

namespace Sensors_WPF__.NET_03._1_.Migrations
{
    [DbContext(typeof(SensorsDbContext))]
    [Migration("20240322200927_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sensors_WPF__.NET_03._1_.Sensors.Sensor", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SensorId"));

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SensorId");

                    b.ToTable("Sensors");

                    b.HasData(
                        new
                        {
                            SensorId = 1,
                            SensorType = "Sensor №1"
                        },
                        new
                        {
                            SensorId = 2,
                            SensorType = "Sensor №2"
                        },
                        new
                        {
                            SensorId = 3,
                            SensorType = "Sensor №3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
