// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sensors_WPF__.NET_03._1_.Sensors;

#nullable disable

namespace Sensors_WPF__.NET_03._1_.Migrations
{
    [DbContext(typeof(SensorsDbContext))]
    [Migration("20240325082426_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sensors_WPF__.NET_03._1_.Sensors.Sensor", b =>
                {
                    b.Property<Guid>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TimeInterval")
                        .HasColumnType("time");

                    b.HasKey("SensorId");

                    b.ToTable("Sensors");

                    b.HasData(
                        new
                        {
                            SensorId = new Guid("2e3e0618-291c-4226-8414-bdd8c6d5bfcc"),
                            SensorType = "Sensor №1",
                            TimeInterval = new TimeSpan(0, 0, 0, 5, 0)
                        },
                        new
                        {
                            SensorId = new Guid("61311d52-f34a-465d-9f1e-93038e303aa3"),
                            SensorType = "Sensor №2",
                            TimeInterval = new TimeSpan(0, 0, 0, 2, 0)
                        },
                        new
                        {
                            SensorId = new Guid("a7fb2d25-1b73-47e8-a890-0964d4d9a44c"),
                            SensorType = "Sensor №3",
                            TimeInterval = new TimeSpan(0, 0, 0, 4, 0)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
